[package]
name = "decurse"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
waker-fn = "1.1"
decurse_macro = { path = "../decurse_macro/" }
scoped-tls = "1.0"
pfn = "0.1"